#!/bin/sh
# Generate crates/ebcdic/src/tables.rs from glibc iconv (run inside the dev container).
# Each table maps ISO-8859-1 byte -> EBCDIC byte. Both code pages are bijections
# over all 256 values, so the reverse tables are derived at compile time.
set -eu
out=crates/ebcdic/src/tables.rs
all=$(mktemp)
i=0
while [ $i -lt 256 ]; do printf "\\$(printf %03o $i)"; i=$((i+1)); done > "$all"

table() {
  iconv -f ISO-8859-1 -t "$1" "$all" | od -An -v -tx1 | tr -s ' \n' ' ' | sed 's/^ //; s/ $//' \
    | awk '{ for (i = 1; i <= NF; i++) { printf "0x%s,%s", toupper($i), (i == NF ? "" : (i % 16 == 0 ? "\n    " : " ")) } }'
}

{
  echo "// @generated by scripts/gen-codepages.sh from glibc iconv. Do not edit."
  echo "// Index: ISO-8859-1 byte. Value: EBCDIC byte."
  echo
  echo "pub(crate) const LATIN1_TO_CP037: [u8; 256] = ["
  printf "    %s\n" "$(table IBM037)"
  echo "];"
  echo
  echo "pub(crate) const LATIN1_TO_CP1047: [u8; 256] = ["
  printf "    %s\n" "$(table IBM1047)"
  echo "];"
} > "$out"
rm -f "$all"
echo "wrote $out"
